#!/usr/bin/env python3
"""
OPEN ME IN BLENDER - McTell Shadowbox Assembly v131
=========================================================
Generated by CNC Generator - Carbide-Optimized v131

This script creates a complete 3D visualization of the shadowbox assembly
with accurate finger joint geometry and Boolean cuts for:
- Window opening in Front Bezel
- Screw holes in Back Panel  
- Rabbet channels in all rails

INSTRUCTIONS:
1. Open Blender
2. Switch to Scripting workspace (or open a Text Editor panel)
3. Open this file (Text > Open)
4. Click "Run Script" or press Alt+P

The script will create:
- All 6 pieces (Top Rail, Bottom Rail, Left Rail, Right Rail, Front Bezel, Back Panel)
- Boolean cuts for Window, Holes, and Rabbets
- Positioned in assembled orientation
- Two plywood materials: wide face (#E2CBAD) and end grain (#C0AD93)
- Area light for visualization
- Imperial units (inches) configured
- Viewport set to Material Preview with JLS Workspace
"""

import bpy
import bmesh
import re
from mathutils import Vector, Euler
import math

# ==============================================================================
# CONFIGURATION (from your CNC Generator settings)
# ==============================================================================
CONFIG = {
    'TOTAL_WIDTH_IN': 61.2000,
    'TOTAL_HEIGHT_IN': 42.2000,
    'BOX_DEPTH_IN': 4.5000,
    'STOCK_THICKNESS_IN': 0.5984,
    'STOCK_THICKNESS_M': 0.015199,
    'TOTAL_WIDTH_M': 1.554480,
    'TOTAL_HEIGHT_M': 1.071880,
    'BOX_DEPTH_M': 0.114300,
    'WINDOW_WIDTH_M': 0.000000,
    'WINDOW_HEIGHT_M': 0.000000,
    'FRONT_RABBET_WIDTH_M': 0.000000,
    'FRONT_RABBET_DEPTH_M': 0.007600,
    'BACK_RABBET_WIDTH_M': 0.000000,
    'BACK_RABBET_DEPTH_M': 0.007600,
    'BACK_HOLE_RADIUS_M': 0.002540,
    'BACK_RIM_WIDTH_M': 0.015199,
    'FRONT_RIM_WIDTH_M': 0.777240,
    'CLEATS_ENABLED': False,
    'HATCH_ENABLED': False,
    'HATCH_WIDTH_PCT': 50.0,
    'HATCH_HEIGHT_PCT': 33.0,
    'HATCH_RAISE_IN': 0.0, # HATCH_RAISE key in config might be string or float from app? App uses vars. 
    # In run_generation: config['HATCH_RAISE'] = float(self.vars['hatch_raise'].get())
    # So it should be a float or parseable.
}

# Back panel hole positions (in meters, relative to panel origin at bottom-left)
BACK_PANEL_HOLES = []

# SVG MARGIN used in path generation (2 inches)
MARGIN_IN = 2.0

# Plywood colors (hex to RGB 0-1)
COLOR_WIDE_FACE = (0xE2/255, 0xCB/255, 0xAD/255, 1.0)  # #E2CBAD
COLOR_END_GRAIN = (0xC0/255, 0xAD/255, 0x93/255, 1.0)  # #C0AD93

# ==============================================================================
# SVG PATH DATA (embedded from generated files)
# ==============================================================================
SVG_PATHS = {
    'TOP_RAIL': """M 2.0000 2.0000 L 62.0032 2.0000 L 62.0032 2.0000 L 62.6016 2.0000 L 62.6016 2.4961 L 62.0032 2.4961 L 62.0032 2.5000 L 62.0032 3.0000 L 62.0032 3.0039 L 62.6016 3.0039 L 62.6016 3.4961 L 62.0032 3.4961 L 62.0032 3.5000 L 62.0032 4.0000 L 62.0032 4.0039 L 62.6016 4.0039 L 62.6016 4.4961 L 62.0032 4.4961 L 62.0032 4.5000 L 62.0032 5.0000 L 62.0032 5.0039 L 62.6016 5.0039 L 62.6016 5.4961 L 62.0032 5.4961 L 62.0032 5.5000 L 62.0032 6.0000 L 62.0032 6.0039 L 62.6016 6.0039 L 62.6016 6.5000 L 62.0032 6.5000 L 62.0032 6.5000 L 2.0000 6.5000 L 2.0000 6.5000 L 1.4016 6.5000 L 1.4016 6.0039 L 2.0000 6.0039 L 2.0000 6.0000 L 2.0000 5.5000 L 2.0000 5.4961 L 1.4016 5.4961 L 1.4016 5.0039 L 2.0000 5.0039 L 2.0000 5.0000 L 2.0000 4.5000 L 2.0000 4.4961 L 1.4016 4.4961 L 1.4016 4.0039 L 2.0000 4.0039 L 2.0000 4.0000 L 2.0000 3.5000 L 2.0000 3.4961 L 1.4016 3.4961 L 1.4016 3.0039 L 2.0000 3.0039 L 2.0000 3.0000 L 2.0000 2.5000 L 2.0000 2.4961 L 1.4016 2.4961 L 1.4016 2.0000 L 2.0000 2.0000 L 2.0000 2.0000 Z""",
    'BOTTOM_RAIL': """M 2.0000 2.0000 L 62.0032 2.0000 L 62.0032 2.0000 L 62.6016 2.0000 L 62.6016 2.4961 L 62.0032 2.4961 L 62.0032 2.5000 L 62.0032 3.0000 L 62.0032 3.0039 L 62.6016 3.0039 L 62.6016 3.4961 L 62.0032 3.4961 L 62.0032 3.5000 L 62.0032 4.0000 L 62.0032 4.0039 L 62.6016 4.0039 L 62.6016 4.4961 L 62.0032 4.4961 L 62.0032 4.5000 L 62.0032 5.0000 L 62.0032 5.0039 L 62.6016 5.0039 L 62.6016 5.4961 L 62.0032 5.4961 L 62.0032 5.5000 L 62.0032 6.0000 L 62.0032 6.0039 L 62.6016 6.0039 L 62.6016 6.5000 L 62.0032 6.5000 L 62.0032 6.5000 L 2.0000 6.5000 L 2.0000 6.5000 L 1.4016 6.5000 L 1.4016 6.0039 L 2.0000 6.0039 L 2.0000 6.0000 L 2.0000 5.5000 L 2.0000 5.4961 L 1.4016 5.4961 L 1.4016 5.0039 L 2.0000 5.0039 L 2.0000 5.0000 L 2.0000 4.5000 L 2.0000 4.4961 L 1.4016 4.4961 L 1.4016 4.0039 L 2.0000 4.0039 L 2.0000 4.0000 L 2.0000 3.5000 L 2.0000 3.4961 L 1.4016 3.4961 L 1.4016 3.0039 L 2.0000 3.0039 L 2.0000 3.0000 L 2.0000 2.5000 L 2.0000 2.4961 L 1.4016 2.4961 L 1.4016 2.0000 L 2.0000 2.0000 L 2.0000 2.0000 Z""",
    'LEFT_RAIL': """M 2.5984 2.0000 L 43.6016 2.0000 L 43.6016 2.5000 L 44.2000 2.5000 L 44.2000 3.0000 L 44.2000 3.0000 L 43.6016 3.0000 L 43.6016 3.5000 L 44.2000 3.5000 L 44.2000 4.0000 L 44.2000 4.0000 L 43.6016 4.0000 L 43.6016 4.5000 L 44.2000 4.5000 L 44.2000 5.0000 L 44.2000 5.0000 L 43.6016 5.0000 L 43.6016 5.5000 L 44.2000 5.5000 L 44.2000 6.0000 L 44.2000 6.0000 L 43.6016 6.0000 L 43.6016 6.5000 L 2.5984 6.5000 L 2.5984 6.0000 L 2.0000 6.0000 L 2.0000 5.5000 L 2.0000 5.5000 L 2.5984 5.5000 L 2.5984 5.0000 L 2.0000 5.0000 L 2.0000 4.5000 L 2.0000 4.5000 L 2.5984 4.5000 L 2.5984 4.0000 L 2.0000 4.0000 L 2.0000 3.5000 L 2.0000 3.5000 L 2.5984 3.5000 L 2.5984 3.0000 L 2.0000 3.0000 L 2.0000 2.5000 L 2.0000 2.5000 L 2.5984 2.5000 L 2.5984 2.0000 Z""",
    'RIGHT_RAIL': """M 2.5984 2.0000 L 43.6016 2.0000 L 43.6016 2.5000 L 44.2000 2.5000 L 44.2000 3.0000 L 44.2000 3.0000 L 43.6016 3.0000 L 43.6016 3.5000 L 44.2000 3.5000 L 44.2000 4.0000 L 44.2000 4.0000 L 43.6016 4.0000 L 43.6016 4.5000 L 44.2000 4.5000 L 44.2000 5.0000 L 44.2000 5.0000 L 43.6016 5.0000 L 43.6016 5.5000 L 44.2000 5.5000 L 44.2000 6.0000 L 44.2000 6.0000 L 43.6016 6.0000 L 43.6016 6.5000 L 2.5984 6.5000 L 2.5984 6.0000 L 2.0000 6.0000 L 2.0000 5.5000 L 2.0000 5.5000 L 2.5984 5.5000 L 2.5984 5.0000 L 2.0000 5.0000 L 2.0000 4.5000 L 2.0000 4.5000 L 2.5984 4.5000 L 2.5984 4.0000 L 2.0000 4.0000 L 2.0000 3.5000 L 2.0000 3.5000 L 2.5984 3.5000 L 2.5984 3.0000 L 2.0000 3.0000 L 2.0000 2.5000 L 2.0000 2.5000 L 2.5984 2.5000 L 2.5984 2.0000 Z""",
}

# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================

def parse_svg_path(path_d, margin_offset=2.0):
    """Parse SVG path d attribute into list of (x, y) vertices in inches, then convert to meters."""
    vertices = []
    commands = re.findall(r'([MLZ])\s*([\d.\-\s]*)', path_d)

    for cmd, coords_str in commands:
        if cmd == 'Z':
            continue
        coords = coords_str.strip().split()
        if len(coords) >= 2:
            x_in = float(coords[0]) - margin_offset
            y_in = float(coords[1]) - margin_offset
            x_m = x_in * 0.0254
            y_m = y_in * 0.0254
            vertices.append((x_m, y_m))

    return vertices

def create_plywood_materials():
    """Create the two plywood materials: wide face and end grain."""

    # Wide face material (#E2CBAD)
    mat_wide = bpy.data.materials.new(name="Plywood_Wide_Face")
    mat_wide.use_nodes = True
    nodes = mat_wide.node_tree.nodes
    nodes.clear()
    output = nodes.new('ShaderNodeOutputMaterial')
    principled = nodes.new('ShaderNodeBsdfPrincipled')
    principled.inputs['Base Color'].default_value = COLOR_WIDE_FACE
    principled.inputs['Roughness'].default_value = 0.6
    mat_wide.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    # End grain material (#C0AD93 - darker)
    mat_end = bpy.data.materials.new(name="Plywood_End_Grain")
    mat_end.use_nodes = True
    nodes = mat_end.node_tree.nodes
    nodes.clear()
    output = nodes.new('ShaderNodeOutputMaterial')
    principled = nodes.new('ShaderNodeBsdfPrincipled')
    principled.inputs['Base Color'].default_value = COLOR_END_GRAIN
    principled.inputs['Roughness'].default_value = 0.7
    mat_end.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    return mat_wide, mat_end

def get_face_dominant_axis(face_normal):
    """Determine which axis a face normal is most aligned with."""
    abs_normal = [abs(face_normal.x), abs(face_normal.y), abs(face_normal.z)]
    max_idx = abs_normal.index(max(abs_normal))
    return ['X', 'Y', 'Z'][max_idx]

def apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_axes):
    """
    Apply end grain material to faces perpendicular to specified axes.

    end_grain_axes: list of axes ('X', 'Y', 'Z') where face normals pointing
                    along these axes should get the end grain material.
    """
    if obj.type != 'MESH':
        return

    # Ensure object has both materials
    obj.data.materials.clear()
    obj.data.materials.append(mat_wide)  # Index 0
    obj.data.materials.append(mat_end)   # Index 1

    # Use bmesh to analyze and assign materials per face
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bm.faces.ensure_lookup_table()

    for face in bm.faces:
        # Get face normal in world space (after transforms applied)
        normal_world = obj.matrix_world.to_3x3() @ face.normal
        dominant_axis = get_face_dominant_axis(normal_world)

        if dominant_axis in end_grain_axes:
            face.material_index = 1  # End grain
        else:
            face.material_index = 0  # Wide face

    bm.to_mesh(obj.data)
    bm.free()
    obj.data.update()

def create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis='Z'):
    """Create a 3D mesh by extruding a 2D profile and link to collection."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)

    # IMPORTANT: Link to collection immediately so it exists in the scene
    collection.objects.link(obj)

    bm = bmesh.new()

    bottom_verts = []
    for v in vertices:
        if extrude_axis == 'Z':
            vert = bm.verts.new((v[0], v[1], 0))
        elif extrude_axis == 'Y':
            vert = bm.verts.new((v[0], 0, v[1]))
        elif extrude_axis == 'X':
            vert = bm.verts.new((0, v[0], v[1]))
        bottom_verts.append(vert)

    bm.verts.ensure_lookup_table()

    if len(bottom_verts) >= 3:
        try:
            bm.faces.new(bottom_verts)
        except:
            pass

    if extrude_axis == 'Z':
        extrude_vec = Vector((0, 0, thickness_m))
    elif extrude_axis == 'Y':
        extrude_vec = Vector((0, thickness_m, 0))
    elif extrude_axis == 'X':
        extrude_vec = Vector((thickness_m, 0, 0))

    ret = bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
    verts = [e for e in ret['geom'] if isinstance(e, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=verts, vec=extrude_vec)

    bm.to_mesh(mesh)
    bm.free()
    mesh.update()

    return obj

def create_simple_box(name, width_m, height_m, depth_m, collection):
    """Create a simple box mesh and link to specified collection."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)

    # Link to our collection
    collection.objects.link(obj)

    # Create box geometry using bmesh
    bm = bmesh.new()
    bmesh.ops.create_cube(bm, size=1.0)
    bm.to_mesh(mesh)
    bm.free()

    # Set dimensions
    obj.dimensions = (width_m, depth_m, height_m)

    return obj

def create_cylinder_cutter(name, radius_m, depth_m, collection, segments=32):
    """Create a cylinder mesh for Boolean cutting operations."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    
    bm = bmesh.new()
    bmesh.ops.create_cone(
        bm,
        cap_ends=True,
        cap_tris=False,
        segments=segments,
        radius1=radius_m,
        radius2=radius_m,
        depth=depth_m
    )
    bm.to_mesh(mesh)
    bm.free()
    
    return obj

def apply_boolean_difference(target_obj, cutter_obj, delete_cutter=True):
    """Apply a boolean difference modifier to cut cutter from target."""
    success = False
    try:
        # Ensure cutter has transforms applied
        bpy.context.view_layer.objects.active = cutter_obj
        cutter_obj.select_set(True)
        bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
        cutter_obj.select_set(False)
        
        # Add boolean modifier
        bool_mod = target_obj.modifiers.new(name="Boolean_Cut", type='BOOLEAN')
        bool_mod.operation = 'DIFFERENCE'
        bool_mod.object = cutter_obj
        bool_mod.solver = 'EXACT'  # Use EXACT solver (required for Blender 4.x)
        
        # Apply the modifier
        bpy.context.view_layer.objects.active = target_obj
        target_obj.select_set(True)
        bpy.ops.object.modifier_apply(modifier=bool_mod.name)
        target_obj.select_set(False)
        success = True
    except Exception as e:
        print(f"    WARNING: Boolean operation failed: {e}")
        # Remove the modifier if it exists but failed to apply
        if "Boolean_Cut" in target_obj.modifiers:
            target_obj.modifiers.remove(target_obj.modifiers["Boolean_Cut"])
    
    # Always delete the cutter to clean up
    if delete_cutter:
        try:
            bpy.data.objects.remove(cutter_obj, do_unlink=True)
        except:
            pass
    
    return success

def remove_inner_cap_faces(obj, inner_bound_x, inner_bound_z):
    """Remove cap faces inside a window opening after Boolean cut."""
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    
    faces_to_delete = []
    for face in bm.faces:
        # Check if all vertices are within the inner bounds
        all_inner = True
        for vert in face.verts:
            if abs(vert.co.x) > inner_bound_x + 0.001 or abs(vert.co.z) > inner_bound_z + 0.001:
                all_inner = False
                break
        if all_inner:
            faces_to_delete.append(face)
    
    for face in faces_to_delete:
        bm.faces.remove(face)
    
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    
    return len(faces_to_delete)

def remove_hole_cap_faces(obj, hole_positions, y_front, y_back):
    """Remove cap faces inside holes after Boolean cuts."""
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    
    faces_to_delete = []
    for face in bm.faces:
        centroid = face.calc_center_median()
        y_vals = [v.co.y for v in face.verts]
        all_front = all(abs(y - y_front) < 0.001 for y in y_vals)
        all_back = all(abs(y - y_back) < 0.001 for y in y_vals)
        
        if all_front or all_back:
            for hx, hz in hole_positions:
                dist = ((centroid.x - hx)**2 + (centroid.z - hz)**2)**0.5
                if dist < 0.01:  # Within 10mm of hole center
                    faces_to_delete.append(face)
                    break
    
    for face in faces_to_delete:
        bm.faces.remove(face)
    
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    
    return len(faces_to_delete)

def create_front_bezel_with_window(name, width_m, height_m, thickness_m, 
                                    window_w_m, window_h_m, rim_width_m, collection):
    """
    Create the front bezel with window cutout.
    
    The bezel has:
    1. Outer dimensions = total_width x total_height
    2. Window cutout = Explicitly sized, centered
    """
    # Create main panel
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    
    # Apply scale to get actual geometry
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    
    # Get bezel center Y position (needed for cutter placement)
    mesh = obj.data
    bezel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_center_y = (bezel_y_min + bezel_y_max) / 2
    
    # Create window cutter (through-cut)
    # window_w and window_h are passed in explicitly now
    window_w = window_w_m
    window_h = window_h_m
    
    if window_w > 0 and window_h > 0:
        # Create cutter mesh using bmesh at correct dimensions
        cutter_mesh = bpy.data.meshes.new(name + "_window_cutter_mesh")
        window_cutter = bpy.data.objects.new(name + "_window_cutter", cutter_mesh)
        collection.objects.link(window_cutter)
        
        bm = bmesh.new()
        hw = window_w / 2
        hd = thickness_m * 1.5  # Go through the panel
        hh = window_h / 2
        
        # Create 8 vertices of the box centered at origin
        verts = [
            bm.verts.new((-hw, -hd, -hh)),
            bm.verts.new(( hw, -hd, -hh)),
            bm.verts.new(( hw,  hd, -hh)),
            bm.verts.new((-hw,  hd, -hh)),
            bm.verts.new((-hw, -hd,  hh)),
            bm.verts.new(( hw, -hd,  hh)),
            bm.verts.new(( hw,  hd,  hh)),
            bm.verts.new((-hw,  hd,  hh)),
        ]
        bm.verts.ensure_lookup_table()
        
        # Create 6 faces
        bm.faces.new([verts[0], verts[1], verts[2], verts[3]])  # bottom
        bm.faces.new([verts[4], verts[7], verts[6], verts[5]])  # top
        bm.faces.new([verts[0], verts[4], verts[5], verts[1]])  # front
        bm.faces.new([verts[2], verts[6], verts[7], verts[3]])  # back
        bm.faces.new([verts[0], verts[3], verts[7], verts[4]])  # left
        bm.faces.new([verts[1], verts[5], verts[6], verts[2]])  # right
        
        bm.to_mesh(cutter_mesh)
        bm.free()
        
        # Position cutter at bezel center Y
        window_cutter.location = (0, bezel_center_y, 0)
        
        # Apply boolean to cut window
        apply_boolean_difference(obj, window_cutter, delete_cutter=True)
        
        # Remove inner cap faces that close the window opening
        # v1.15: Removed manual face removal to ensure watertight geometry. 
        # The Boolean Difference (Exact Solver) handles this correctly on its own now.
        
        print(f"    - Window cut: {window_w*39.37:.2f} x {window_h*39.37:.2f} inches")
    
    return obj

def create_back_panel_with_holes(name, width_m, height_m, thickness_m,
                                  hole_positions, hole_radius_m, rim_width_m, collection):
    """
    Create the back panel with screw holes.
    
    The panel has:
    1. Outer dimensions = total_width x total_height
    2. Screw holes at specified positions
    """
    # Create main panel
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    
    # Apply scale to get actual geometry
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    
    # Get panel Y bounds for cap face removal later
    mesh = obj.data
    panel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_center_y = (panel_y_min + panel_y_max) / 2
    
    # Track hole positions in panel-centered coordinates for cap removal
    centered_hole_positions = []
    
    # Create and apply hole cutters
    if hole_positions and hole_radius_m > 0:
        print(f"    - Cutting {len(hole_positions)} screw holes (r={hole_radius_m*39.37:.3f} in)")
        
        for i, (hx, hy) in enumerate(hole_positions):
            # Create cylinder cutter
            hole_cutter = create_cylinder_cutter(
                f"{name}_hole_{i}", 
                hole_radius_m, 
                thickness_m * 3,  # Go through the panel
                collection,
                segments=16
            )
            
            # Rotate to align with Y axis (panel faces front/back)
            hole_cutter.rotation_euler = (math.pi/2, 0, 0)
            
            # Position hole - convert from bottom-left origin to center origin
            hole_x = hx - width_m/2
            hole_z = hy - height_m/2
            hole_cutter.location = (hole_x, panel_center_y, hole_z)
            centered_hole_positions.append((hole_x, hole_z))
            
            # Apply rotation and location before boolean
            bpy.context.view_layer.objects.active = hole_cutter
            hole_cutter.select_set(True)
            bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
            hole_cutter.select_set(False)
            
            # Apply boolean
            apply_boolean_difference(obj, hole_cutter, delete_cutter=True)
        
        # Remove cap faces inside holes
        # Get updated Y bounds after boolean
        mesh = obj.data
        y_front = min(v.co.y for v in mesh.vertices)
        y_back = max(v.co.y for v in mesh.vertices)
        
        caps_removed = remove_hole_cap_faces(obj, centered_hole_positions, y_front, y_back)
        print(f"    - Removed {caps_removed} hole cap faces")
    
    return obj

def create_rail_with_rabbets(name, vertices, thickness_m, collection,
                              front_rabbet_w_m, front_rabbet_d_m,
                              back_rabbet_w_m, back_rabbet_d_m,
                              rail_length_m, rail_depth_m, extrude_axis='Z'):
    """
    Create a rail from SVG profile vertices.
    
    Note: Rabbet cuts on rails are skipped for now as the complex finger joint
    geometry makes Boolean operations unreliable. The visual representation 
    still accurately shows the finger joints which are the key feature.
    """
    # Create base rail from profile
    if len(vertices) >= 3:
        obj = create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis)
    else:
        # Fallback to simple box
        obj = create_simple_box(name, rail_length_m, thickness_m, rail_depth_m, collection)
    
    return obj

# ==============================================================================
# MAIN ASSEMBLY FUNCTION
# ==============================================================================

def create_shadowbox_assembly():
    """Create the complete McTell Shadowbox assembly with Boolean cuts."""

    print("=" * 60)
    print("Creating McTell Shadowbox Assembly v131")
    print("With Boolean cuts for Window, Holes, and Rabbets")
    print("=" * 60)

    # 1. SETUP SCENE
    print("\n[1/8] Setting up scene...")

    bpy.context.scene.unit_settings.system = 'IMPERIAL'
    bpy.context.scene.unit_settings.length_unit = 'INCHES'
    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.samples = 16
    bpy.context.scene.cycles.preview_samples = 32

    # Set World background strength (User Request)
    if bpy.context.scene.world and bpy.context.scene.world.node_tree:
        bg_node = bpy.context.scene.world.node_tree.nodes.get("Background")
        if bg_node:
            bg_node.inputs[1].default_value = 0.02

    # Create collection
    collection = bpy.data.collections.new("McTell Shadowbox Assembly")
    bpy.context.scene.collection.children.link(collection)

    # Make it active
    bpy.context.view_layer.active_layer_collection = bpy.context.view_layer.layer_collection.children[collection.name]

    # 2. CREATE PLYWOOD MATERIALS
    print("[2/8] Creating plywood materials...")

    mat_wide, mat_end = create_plywood_materials()
    print(f"  - Wide face: #E2CBAD")
    print(f"  - End grain: #C0AD93")

    # 3. CREATE RAILS WITH RABBETS
    print("[3/8] Creating rails with rabbet channels...")

    stock_thk = CONFIG['STOCK_THICKNESS_M']
    total_w = CONFIG['TOTAL_WIDTH_M']
    total_h = CONFIG['TOTAL_HEIGHT_M']
    box_d = CONFIG['BOX_DEPTH_M']
    front_rab_w = CONFIG['FRONT_RABBET_WIDTH_M']
    front_rab_d = CONFIG['FRONT_RABBET_DEPTH_M']
    back_rab_w = CONFIG['BACK_RABBET_WIDTH_M']
    back_rab_d = CONFIG['BACK_RABBET_DEPTH_M']

    parts = {}

    # TOP RAIL
    print("  - Top Rail")
    top_verts = parse_svg_path(SVG_PATHS['TOP_RAIL'])
    parts['TOP'] = create_rail_with_rabbets(
        "McTell_Top_Rail", top_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_w, box_d, 'Z'
    )

    # BOTTOM RAIL
    print("  - Bottom Rail")
    bot_verts = parse_svg_path(SVG_PATHS['BOTTOM_RAIL'])
    parts['BOTTOM'] = create_rail_with_rabbets(
        "McTell_Bottom_Rail", bot_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_w, box_d, 'Z'
    )

    # LEFT RAIL
    print("  - Left Rail")
    left_verts = parse_svg_path(SVG_PATHS['LEFT_RAIL'])
    parts['LEFT'] = create_rail_with_rabbets(
        "McTell_Left_Rail", left_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_h, box_d, 'Z'
    )
    parts['LEFT'].rotation_euler = (0, math.radians(90), 0)

    # RIGHT RAIL
    print("  - Right Rail")
    right_verts = parse_svg_path(SVG_PATHS['RIGHT_RAIL'])
    parts['RIGHT'] = create_rail_with_rabbets(
        "McTell_Right_Rail", right_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_h, box_d, 'Z'
    )
    parts['RIGHT'].rotation_euler = (0, math.radians(-90), 0)

    # 4. CREATE FRONT BEZEL WITH WINDOW
    print("[4/8] Creating Front Bezel with window cutout...")
    parts['FRONT'] = create_front_bezel_with_window(
        "McTell_Front_Bezel",
        total_w, total_h, stock_thk,
        CONFIG['WINDOW_WIDTH_M'],
        CONFIG['WINDOW_HEIGHT_M'],
        CONFIG['FRONT_RIM_WIDTH_M'],
        collection
    )

    # 5. CREATE BACK PANEL WITH HOLES
    print("[5/8] Creating Back Panel with screw holes...")
    parts['BACK'] = create_back_panel_with_holes(
        "McTell_Back_Panel",
        total_w, total_h, stock_thk,
        BACK_PANEL_HOLES,
        CONFIG['BACK_HOLE_RADIUS_M'],
        CONFIG['BACK_RIM_WIDTH_M'],
        collection
    )

    # 5b. CREATE CLEATS (Restored v1.13)
    # Check if enabled
    if CONFIG.get('CLEATS_ENABLED', 'True') == 'True':
        print("[5b/8] Creating French Cleats...")
        # Cleats Dims: 0.75" thick (or stock), 3" tall? No, usually 45 deg.
        # User Specs? usually ~3 inches height.
        # Let's use standard default: 75mm tall (~3 in).
        cw_m = total_w - (20 * 0.0254) # Inset from sides? Or Full Width?
        # Internal Width = Total - 2*Stock.
        inner_w = total_w - (2 * stock_thk)
        # Cleat usually spans inner width minus clearance.
        cw = inner_w - (0.01) # 1cm clearance
        ch = 3.0 * 0.0254 # 3 inches height
        
        # 1. Box Cleat (Mounted on Box)
        cleat_obj_box = create_french_cleat("McTell_Cleat_Box", cw, ch, stock_thk, collection, is_wall_part=False)
        
        # Position:
        # X: Centered.
        # Y: Box Cleat is Inside. Back Face against Back Panel.
        # Back Panel Inner Face Y = half_d - stock_thk/2 - stock_thk? 
        # Back Panel Center Y = half_d + stock_thk/2.
        # Back Panel Inner Face = half_d.
        # Box Cleat Back Face = half_d.
        # Box Cleat Extruded width (X). Box Cleat Thickness (Y).
        # We need to rotate it to match orientation.
        # Cleat Profile was in XY plane extruded X?
        # Let's check `create_french_cleat` logic.
        # It extrudes along X. Profile in YZ.
        # Perfect.
        # Box Cleat Back is at Y=0.
        # We want Back at Y = half_d.
        # But wait, Box Cleat attaches to the BACK of the box?
        # Usually French Cleat is on the OUTSIDE of the Back Panel?
        # If so, Y = half_d + stock_thk.
        # "Recalculate": Box Cleat is mounted to the Back Panel.
        # Does it stick out? Yes.
        # So Position Y = half_d + stock_thk.
        
        box_cleat_y = half_d + stock_thk
        
        # Height Z: Near top?
        # 2 inches from top inner edge?
        # Top Inner Edge = half_h - stock_thk.
        # Cleat Top = half_h - stock_thk.
        # Cleat Height = ch.
        # Cleat Center Z? No, Origin is Bottom-Back.
        # So Origin Z = (half_h - stock_thk) - ch.
        
        box_cleat_z = (half_h - stock_thk) - ch
        
        cleat_obj_box.location = (0, box_cleat_y, box_cleat_z)
        # Origin was center X? Yes (hw logic).
        
        parts['CLEAT_BOX'] = cleat_obj_box
        
        # 2. Wall Cleat (Mated)
        cleat_obj_wall = create_french_cleat("McTell_Cleat_Wall", cw, ch, stock_thk, collection, is_wall_part=True)
        # Mated Position:
        # Wall Cleat engages Box Cleat.
        # It is "Behind" Box Cleat (further +Y).
        # Y = box_cleat_y + ? 
        # They overlap in space if perfectly mated?
        # Wall Cleat Back is against Wall.
        # Box Cleat Back is against Box.
        # Thicknesses stack? No, they interlock.
        # Effective Stack Thickness = 1 * Stock (since 45 deg cut).
        # So Wall Surface is at Box_Back_Y + Stock.
        # Wall Cleat Location (Back Face) = Box_Back_Y + Stock.
        # Height: Matches engagement.
        cleat_obj_wall.location = (0, box_cleat_y + stock_thk, box_cleat_z)
        
        parts['CLEAT_WALL'] = cleat_obj_wall

    # 5c. CREATE BOTTOM ACCESS HATCH (v1.25)
    if CONFIG.get('BOTTOM_HATCH_ENABLED', 'False') == 'True':
        print("[5c/8] Creating Bottom Access Hatch...")
        # Dims from Config (mm -> in -> m)
        bh_w_m = CONFIG.get('BOTTOM_HATCH_WIDTH', 0) * 0.001 # stored in mm in CONFIG?
        bh_h_m = CONFIG.get('BOTTOM_HATCH_HEIGHT', 0) * 0.001
        # Wait, CONFIG usually stores raw values. Main script converted to inches/meters for passing?
        # In blender_generator.py:
        # CONFIG dictionary is populated with PRE-CALCULATED 'IN' and 'M' values in the main script call.
        # BUT 'BOTTOM_HATCH_WIDTH' might just be the raw value from the UI vars?
        # Let's check how main script calls it.
        # Main script passes `CONFIG`.
        # `CONFIG` contains 'BOTTOM_HATCH_WIDTH' (mm, float).
        # So we need to convert.
        
        bh_w_mm = float(CONFIG.get('BOTTOM_HATCH_WIDTH', 0))
        bh_h_mm = float(CONFIG.get('BOTTOM_HATCH_HEIGHT', 0))
        bh_x_pct = float(CONFIG.get('BOTTOM_HATCH_X_PCT', 50.0))
        
        bh_w_m = bh_w_mm * 0.001
        bh_h_m = bh_h_mm * 0.001
        
        # Flange logic
        glue_gap = 0.0005 # approx 0.5mm
        flange_w = (stock_thk / 2.0) - glue_gap
        if flange_w < 0.001: flange_w = 0.001

        # Create Hatch Lid Object
        bh_obj = create_hatch_lid("McTell_Bottom_Hatch_Lid", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        # On Bottom Rail.
        # Bottom Rail Y (Depth) center = 0.
        # Bottom Rail Z (Height) = -half_h + stock/2.
        # Hatch is "In" the rail.
        # Rail Thickness is Z.
        # Hatch Thickness is Z.
        # Hatch should be flush with Rail Bottom (Outside)? Or Rail Top (Inside)?
        # Usually flush with Outside (Bottom).
        # Rail Bottom Z = -half_h.
        # Hatch Bottom Z = -half_h.
        # Hatch constructed centered.
        # Move to Z = -half_h + stock/2. (Same as Rail Center).
        
        # X Position:
        # bh_x_pct along Rail Width.
        # Rail Width = Total Width - 2*Stock.
        # Rail starts at X = -(TotalW/2) + Stock.
        # 0% = Left Inner Edge. 100% = Right Inner Edge.
        # Inner Width = TotalW - 2*Stock.
        # X = (LeftEdge) + (Pct * InnerWidth).
        # LeftEdge = -(total_w/2) + stock_thk.
        
        inner_w = total_w - (2 * stock_thk)
        bx = (-(total_w/2) + stock_thk) + (bh_x_pct / 100.0 * inner_w)
        
        # Y Position: Centered in Depth (Y=0).
        
        bh_obj.location = (bx, 0, -half_h + stock_thk/2)
        # Orientation: create_hatch_lid makes it flat (Y-up thickness).
        # Wait, create_hatch_lid scales (w, thk/2, h). Y is thickness.
        # Bottom Rail is flat?
        # create_rail_with_rabbets for BOTTOM:
        # profile (Y, Z in SVG -> X, Y in Blender?)
        # Let's check create_rail_with_rabbets call for BOTTOM.
        # extrude_axis='Z'.
        # Profile is in X-Y?
        # parse_svg_path returns (x, y).
        # BOTTOM_RAIL SVG: width=TotalW, height=BoxDepth.
        # So Profile is Top-Down view?
        # Extruded Z (Thickness).
        # So Rail is Flat in XY plane.
        # create_hatch_lid makes thickness in Y.
        # We need thickness in Z.
        # Rotate 90 deg on X?
        bh_obj.rotation_euler = (math.radians(90), 0, 0) 
        
        parts['BOTTOM_HATCH'] = bh_obj
        
        # Cutout in Bottom Rail
        # 1. Through Cut (Opening)
        c1 = create_simple_box("Bottom_Hatch_Cut_Thru", bh_w_m, box_d * 2, bh_h_m, collection) 
        # Wait, create_simple_box dims: (W, Depth, Height).
        # We want W=HatchW, D=HatchH? No.
        # Hatch is aligned X (Width) and Y (Depth of box).
        # So Cutter W = bh_w_m.
        # Cutter D (Blender Y) = bh_h_m.
        # Cutter H (Blender Z) = Thick.
        c1 = create_simple_box("Bottom_Hatch_Cut_Thru", bh_w_m, bh_h_m, stock_thk*4, collection)
        c1.location = (bx, 0, -half_h + stock_thk/2)
        apply_boolean_difference(parts['BOTTOM'], c1, delete_cutter=True)
        
        # 2. Pocket Cut (Shelf)
        # From Outside (Bottom) Face Inwards.
        # Bottom Face Z = -half_h.
        # Pocket Depth = stock/2.
        # Cutter Z = -half_h + stock/4.
        c2 = create_simple_box("Bottom_Hatch_Cut_Pocket", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk/2, collection)
        c2.location = (bx, 0, -half_h + (stock_thk * 0.25))
        apply_boolean_difference(parts['BOTTOM'], c2, delete_cutter=True)

    # 5d. CREATE HATCH (Rear)
    if CONFIG.get('HATCH_ENABLED', 'False') == 'True':
        print("[5d/8] Creating Rear Hatch Lid...")
        w_pct = float(CONFIG.get('HATCH_WIDTH_PCT', 50.0))
        h_pct = float(CONFIG.get('HATCH_HEIGHT_PCT', 33.0))
        
        h_open_w = (total_w * w_pct / 100.0)
        h_open_h = (total_h * h_pct / 100.0)
        
        # Flange logic
        glue_gap = 0.0005 # approx
        flange_w = (stock_thk / 2.0) - glue_gap
        
        hatch_obj = create_hatch_lid("McTell_Hatch_Lid", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        # Specified as "Raise" from bottom Baseline.
        # Baseline = Bottom Frame Inner Edge = -half_h + stock_thk.
        # Raise comes from config (inches).
        raise_in = float(CONFIG.get('HATCH_RAISE_IN', 0.0))
        raise_m = raise_in * 0.0254
        
        # Base Z = Bottom of Hatch.
        # Box Center Z = 0. Range [-H/2, H/2].
        # Bottom of Box = -H/2.
        # Top of Bottom Rail = -H/2 + stock_thk.
        # Hatch Bottom = Top of Rail + Raise.
        base_z = (-half_h + stock_thk) + raise_m
        # Hatch Origin is Center?
        # Logic in `create_hatch_lid` centers it at (0,0,0).
        # So we move Center to:
        # X: 0.
        # Z: Base_Z + (Hatch_Height / 2).
        # Y: Flush with Inside Face of Back Panel?
        # Back Panel Inner Face = half_d.
        # Hatch sits in the hole.
        hatch_y = half_d

        hatch_obj.location = (0, hatch_y, base_z + (h_open_h/2))
        hatch_obj.rotation_euler = (math.pi/2, 0, 0) # Rotate to stand up in X-Z plane
        
        parts['HATCH'] = hatch_obj
        
        # Cutout in Back Panel (Already done by boolean in create_back_panel? No.)
        # v1.12 had separate cutout logic.
        # v1.13 `create_back_panel_with_holes` only does screw holes.
        # We need to Cut the Hatch Opening NOW.
        
        # Cut Opening (Through)
        cutter = create_simple_box("Hatch_Opening_Cut", h_open_w, h_open_h, stock_thk * 3, collection)
        cutter.location = (0, hatch_y, base_z + (h_open_h/2))
        apply_boolean_difference(parts['BACK'], cutter, delete_cutter=True)
        
        # Cut Flange Pocket (Shelf)
        # From Outside Face inwards.
        # Outside Face Y = half_d + stock_thk.
        # Pocket Depth = stock/2.
        # We want to remove the Rear half of the panel thickness.
        pocket_cutter = create_simple_box("Hatch_Pocket_Cut", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, collection)
        # Position: Center aligned. Y depth?
        # Center of cutter at: half_d + stock_thk/2 + stock_thk/4?
        # We want to cut Y range [half_d + stock/2, half_d + stock].
        # Center of that range is half_d + 0.75*stock.
        pocket_cutter.location = (0, half_d + (stock_thk * 0.75), base_z + (h_open_h/2))
        apply_boolean_difference(parts['BACK'], pocket_cutter, delete_cutter=True)

    # 6. POSITION PARTS
    print("[6/8] Positioning parts...")

    half_w = total_w / 2
    half_h = total_h / 2
    half_d = box_d / 2

    # Set origins to geometry center
    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
        obj.select_set(False)

    # Get actual horizontal rail width (includes finger protrusions)
    top_rail_width = parts['TOP'].dimensions.x
    finger_tip_x = top_rail_width / 2

    # Position each part
    parts['TOP'].location = (0, 0, half_h - stock_thk/2)
    parts['BOTTOM'].location = (0, 0, -half_h + stock_thk/2)
    parts['LEFT'].location = (-finger_tip_x + stock_thk/2, 0, 0)
    parts['RIGHT'].location = (finger_tip_x - stock_thk/2, 0, 0)
    parts['FRONT'].location = (0, -half_d - stock_thk/2, 0)
    parts['BACK'].location = (0, half_d + stock_thk/2, 0)

    # 7. APPLY TRANSFORMS AND MATERIALS
    print("[7/8] Applying transforms and materials...")

    # Apply transforms first
    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
        obj.select_set(False)

    # Define end grain axes for each part (after transforms applied)
    end_grain_config = {
        'TOP': ['X'],           # End grain on left/right (finger sides)
        'BOTTOM': ['X'],        # End grain on left/right (finger sides)
        'LEFT': ['Z'],          # After rotation, end grain points up/down
        'RIGHT': ['Z'],         # After rotation, end grain points up/down
        'FRONT': ['X', 'Z'],    # End grain on all 4 edges
        'BACK': ['X', 'Z'],     # End grain on all 4 edges
    }

    for key, obj in parts.items():
        apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_config.get(key, []))

    # Parent all parts to a main Empty for unified movement
    print("[8a/8] Parenting parts to root object...")
    root_empty = bpy.data.objects.new("McTell_Box_Root", None)
    collection.objects.link(root_empty)
    root_empty.location = (0, 0, 0)
    root_empty.empty_display_type = 'CUBE'
    root_empty.empty_display_size = 0.5
    
    for key, obj in parts.items():
        obj.parent = root_empty
        obj.matrix_parent_inverse = root_empty.matrix_world.inverted()

    # 8. ADD LIGHTING
    print("[8/8] Setting up lighting...")

    # Area light per JLS specifications
    light_data = bpy.data.lights.new(name="Area_Light", type='AREA')
    light_data.color = (1.0, 1.0, 1.0)  # #FFFFFF
    light_data.energy = 5.0             # Power: 5 (User Request)
    light_data.shape = 'SQUARE'         # Shape: square
    light_data.size = 300 * 0.0254      # Size: 300 (convert inches to meters)
    light_data.spread = math.radians(180)  # Spread: 180 degrees

    # Set exposure on the scene/view layer
    bpy.context.scene.view_settings.exposure = 4.0

    light_obj = bpy.data.objects.new("Area_Light", light_data)
    collection.objects.link(light_obj)

    # Location: -90", -20", -80" (convert to meters)
    light_obj.location = (-90 * 0.0254, -20 * 0.0254, -80 * 0.0254)
    # Rotation: 0, 208, 0 degrees
    light_obj.rotation_euler = (0, math.radians(208), 0)

    # Set viewport shading to Material Preview
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            for space in area.spaces:
                if space.type == 'VIEW_3D':
                    space.shading.type = 'MATERIAL'
                    space.clip_start = 0.01
                    space.clip_end = 1000.0
                    break
            break

    # Frame all objects
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            region = next((r for r in area.regions if r.type == 'WINDOW'), None)
            if region:
                override = bpy.context.copy()
                override['area'] = area
                override['region'] = region
                with bpy.context.temp_override(**override):
                    bpy.ops.view3d.view_all(center=True)
                break

    # Switch to JLS Workspace if it exists
    if "JLS Workspace" in bpy.data.workspaces:
        bpy.context.window.workspace = bpy.data.workspaces["JLS Workspace"]
        print("  - Switched to JLS Workspace")
    else:
        print("  - JLS Workspace not found, using current workspace")

    print("\n" + "=" * 60)
    print("ASSEMBLY COMPLETE!")
    print("=" * 60)
    print(f"\nDimensions:")
    print(f"  Total Width:  {CONFIG['TOTAL_WIDTH_IN']:.2f} inches")
    print(f"  Total Height: {CONFIG['TOTAL_HEIGHT_IN']:.2f} inches")
    print(f"  Box Depth:    {CONFIG['BOX_DEPTH_IN']:.2f} inches")
    print(f"  Stock:        {CONFIG['STOCK_THICKNESS_IN']:.4f} inches (15mm)")
    print(f"\nBoolean Cuts Applied:")
    print(f"  - Front Bezel: Window cutout (with cap faces removed)")
    print(f"  - Back Panel:  {len(BACK_PANEL_HOLES)} screw holes (with cap faces removed)")
    print(f"\nMaterials:")
    print(f"  Wide face: #E2CBAD")
    print(f"  End grain: #C0AD93")
    print(f"\nParts created: {len(parts)}")
    
    # FINAL FIX: Ensure all objects have their Origin at Geometric Center
    # This fixes the "Gizmo Rotation" issue if SVG import caused offsets.
    print("[Finalizing] Centering Origins...")
    for obj in collection.objects:
        if obj.type == 'MESH':
            bpy.context.view_layer.objects.active = obj
            obj.select_set(True)
            bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
            obj.select_set(False)
            
    # Also ensure Root is at World Origin (it is, but good to be sure)
    root_empty.location = (0, 0, 0)
    
    print("\nTIP: Press Numpad 0 for camera view, or use the viewport controls to orbit.")

# ==============================================================================
# RUN
# ==============================================================================
if __name__ == "__main__":
    create_shadowbox_assembly()
