#!/usr/bin/env python3
"""
OPEN ME IN TRIVISION - McTell Shadowbox Assembly v131
===========================================================
Generated by CNC Generator - Carbide-Optimized v131

This script imports the generated box into an existing Blender scene.
It creates a collection 'BOX GENERATOR' and places all parts there.
It does NOT alter scene lighting, units, or world settings.
"""

import bpy
import bmesh
import re
from mathutils import Vector, Euler
import math

# ==============================================================================
# CONFIGURATION
# ==============================================================================
CONFIG = {
    'TOTAL_WIDTH_IN': 62.4594,
    'TOTAL_HEIGHT_IN': 43.4594,
    'BOX_DEPTH_IN': 5.0984,
    'STOCK_THICKNESS_IN': 0.5984,
    'STOCK_THICKNESS_M': 0.015199,
    'TOTAL_WIDTH_M': 1.586469,
    'TOTAL_HEIGHT_M': 1.103869,
    'BOX_DEPTH_M': 0.129499,
    'WINDOW_WIDTH_M': 1.327404,
    'WINDOW_HEIGHT_M': 0.844804,
    'FRONT_RABBET_WIDTH_M': 0.000000,
    'FRONT_RABBET_DEPTH_M': 0.007600,
    'BACK_RABBET_WIDTH_M': 0.000000,
    'BACK_RABBET_DEPTH_M': 0.007600,
    'BACK_HOLE_RADIUS_M': 0.002540,
    'BACK_RIM_WIDTH_M': 0.015199,
    'FRONT_RIM_WIDTH_M': 0.129532,
}

# Back panel hole positions (in meters)
BACK_PANEL_HOLES = [(0.24459438000000003, 0.36795625333333326), (0.58597038, 0.36795625333333326), (0.9883063799999999, 0.36795625333333326), (1.34187438, 0.36795625333333326)]

# SVG MARGIN used in path generation (2 inches)
MARGIN_IN = 2.0

# Plywood colors
COLOR_WIDE_FACE = (0xE2/255, 0xCB/255, 0xAD/255, 1.0)
COLOR_END_GRAIN = (0xC0/255, 0xAD/255, 0x93/255, 1.0)

# ==============================================================================
# SVG PATH DATA
# ==============================================================================
SVG_PATHS = {
    'TOP_RAIL': """M 2.0000 2.0000 L 63.2626 2.0000 L 63.2626 2.0000 L 63.8610 2.0000 L 63.8610 2.5665 L 63.2626 2.5665 L 63.2626 2.5665 L 63.2626 3.1330 L 63.2626 3.1330 L 63.8610 3.1330 L 63.8610 3.6995 L 63.2626 3.6995 L 63.2626 3.6995 L 63.2626 4.2660 L 63.2626 4.2660 L 63.8610 4.2660 L 63.8610 4.8324 L 63.2626 4.8324 L 63.2626 4.8324 L 63.2626 5.3989 L 63.2626 5.3989 L 63.8610 5.3989 L 63.8610 5.9654 L 63.2626 5.9654 L 63.2626 5.9654 L 63.2626 6.5319 L 63.2626 6.5319 L 63.8610 6.5319 L 63.8610 7.0984 L 63.2626 7.0984 L 63.2626 7.0984 L 2.0000 7.0984 L 2.0000 7.0984 L 1.4016 7.0984 L 1.4016 6.5319 L 2.0000 6.5319 L 2.0000 6.5319 L 2.0000 5.9654 L 2.0000 5.9654 L 1.4016 5.9654 L 1.4016 5.3989 L 2.0000 5.3989 L 2.0000 5.3989 L 2.0000 4.8324 L 2.0000 4.8324 L 1.4016 4.8324 L 1.4016 4.2660 L 2.0000 4.2660 L 2.0000 4.2660 L 2.0000 3.6995 L 2.0000 3.6995 L 1.4016 3.6995 L 1.4016 3.1330 L 2.0000 3.1330 L 2.0000 3.1330 L 2.0000 2.5665 L 2.0000 2.5665 L 1.4016 2.5665 L 1.4016 2.0000 L 2.0000 2.0000 L 2.0000 2.0000 Z""",
    'BOTTOM_RAIL': """M 2.0000 2.0000 L 63.2626 2.0000 L 63.2626 2.0000 L 63.8610 2.0000 L 63.8610 2.5665 L 63.2626 2.5665 L 63.2626 2.5665 L 63.2626 3.1330 L 63.2626 3.1330 L 63.8610 3.1330 L 63.8610 3.6995 L 63.2626 3.6995 L 63.2626 3.6995 L 63.2626 4.2660 L 63.2626 4.2660 L 63.8610 4.2660 L 63.8610 4.8324 L 63.2626 4.8324 L 63.2626 4.8324 L 63.2626 5.3989 L 63.2626 5.3989 L 63.8610 5.3989 L 63.8610 5.9654 L 63.2626 5.9654 L 63.2626 5.9654 L 63.2626 6.5319 L 63.2626 6.5319 L 63.8610 6.5319 L 63.8610 7.0984 L 63.2626 7.0984 L 63.2626 7.0984 L 2.0000 7.0984 L 2.0000 7.0984 L 1.4016 7.0984 L 1.4016 6.5319 L 2.0000 6.5319 L 2.0000 6.5319 L 2.0000 5.9654 L 2.0000 5.9654 L 1.4016 5.9654 L 1.4016 5.3989 L 2.0000 5.3989 L 2.0000 5.3989 L 2.0000 4.8324 L 2.0000 4.8324 L 1.4016 4.8324 L 1.4016 4.2660 L 2.0000 4.2660 L 2.0000 4.2660 L 2.0000 3.6995 L 2.0000 3.6995 L 1.4016 3.6995 L 1.4016 3.1330 L 2.0000 3.1330 L 2.0000 3.1330 L 2.0000 2.5665 L 2.0000 2.5665 L 1.4016 2.5665 L 1.4016 2.0000 L 2.0000 2.0000 L 2.0000 2.0000 Z""",
    'LEFT_RAIL': """M 2.5984 2.0000 L 44.8610 2.0000 L 44.8610 2.5665 L 45.4594 2.5665 L 45.4594 3.1330 L 45.4594 3.1330 L 44.8610 3.1330 L 44.8610 3.6995 L 45.4594 3.6995 L 45.4594 4.2660 L 45.4594 4.2660 L 44.8610 4.2660 L 44.8610 4.8324 L 45.4594 4.8324 L 45.4594 5.3989 L 45.4594 5.3989 L 44.8610 5.3989 L 44.8610 5.9654 L 45.4594 5.9654 L 45.4594 6.5319 L 45.4594 6.5319 L 44.8610 6.5319 L 44.8610 7.0984 L 2.5984 7.0984 L 2.5984 6.5319 L 2.0000 6.5319 L 2.0000 5.9654 L 2.0000 5.9654 L 2.5984 5.9654 L 2.5984 5.3989 L 2.0000 5.3989 L 2.0000 4.8324 L 2.0000 4.8324 L 2.5984 4.8324 L 2.5984 4.2660 L 2.0000 4.2660 L 2.0000 3.6995 L 2.0000 3.6995 L 2.5984 3.6995 L 2.5984 3.1330 L 2.0000 3.1330 L 2.0000 2.5665 L 2.0000 2.5665 L 2.5984 2.5665 L 2.5984 2.0000 Z""",
    'RIGHT_RAIL': """M 2.5984 2.0000 L 44.8610 2.0000 L 44.8610 2.5665 L 45.4594 2.5665 L 45.4594 3.1330 L 45.4594 3.1330 L 44.8610 3.1330 L 44.8610 3.6995 L 45.4594 3.6995 L 45.4594 4.2660 L 45.4594 4.2660 L 44.8610 4.2660 L 44.8610 4.8324 L 45.4594 4.8324 L 45.4594 5.3989 L 45.4594 5.3989 L 44.8610 5.3989 L 44.8610 5.9654 L 45.4594 5.9654 L 45.4594 6.5319 L 45.4594 6.5319 L 44.8610 6.5319 L 44.8610 7.0984 L 2.5984 7.0984 L 2.5984 6.5319 L 2.0000 6.5319 L 2.0000 5.9654 L 2.0000 5.9654 L 2.5984 5.9654 L 2.5984 5.3989 L 2.0000 5.3989 L 2.0000 4.8324 L 2.0000 4.8324 L 2.5984 4.8324 L 2.5984 4.2660 L 2.0000 4.2660 L 2.0000 3.6995 L 2.0000 3.6995 L 2.5984 3.6995 L 2.5984 3.1330 L 2.0000 3.1330 L 2.0000 2.5665 L 2.0000 2.5665 L 2.5984 2.5665 L 2.5984 2.0000 Z""",
}

# ==============================================================================
# HELPER FUNCTIONS (Duplicated for standalone capability)
# ==============================================================================

def parse_svg_path(path_d, margin_offset=2.0):
    vertices = []
    commands = re.findall(r'([MLZ])\s*([\d.\-\s]*)', path_d)
    for cmd, coords_str in commands:
        if cmd == 'Z': continue
        coords = coords_str.strip().split()
        if len(coords) >= 2:
            x_in = float(coords[0]) - margin_offset
            y_in = float(coords[1]) - margin_offset
            x_m = x_in * 0.0254
            y_m = y_in * 0.0254
            vertices.append((x_m, y_m))
    return vertices

def create_plywood_materials():
    # Check if materials already exist to avoid duplicates or use them
    mat_wide = bpy.data.materials.get("Plywood_Wide_Face")
    if not mat_wide:
        mat_wide = bpy.data.materials.new(name="Plywood_Wide_Face")
        mat_wide.use_nodes = True
        nodes = mat_wide.node_tree.nodes
        nodes.clear()
        output = nodes.new('ShaderNodeOutputMaterial')
        principled = nodes.new('ShaderNodeBsdfPrincipled')
        principled.inputs['Base Color'].default_value = COLOR_WIDE_FACE
        principled.inputs['Roughness'].default_value = 0.6
        mat_wide.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    mat_end = bpy.data.materials.get("Plywood_End_Grain")
    if not mat_end:
        mat_end = bpy.data.materials.new(name="Plywood_End_Grain")
        mat_end.use_nodes = True
        nodes = mat_end.node_tree.nodes
        nodes.clear()
        output = nodes.new('ShaderNodeOutputMaterial')
        principled = nodes.new('ShaderNodeBsdfPrincipled')
        principled.inputs['Base Color'].default_value = COLOR_END_GRAIN
        principled.inputs['Roughness'].default_value = 0.7
        mat_end.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    return mat_wide, mat_end

def get_face_dominant_axis(face_normal):
    abs_normal = [abs(face_normal.x), abs(face_normal.y), abs(face_normal.z)]
    max_idx = abs_normal.index(max(abs_normal))
    return ['X', 'Y', 'Z'][max_idx]

def apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_axes):
    if obj.type != 'MESH': return
    if mat_wide.name not in obj.data.materials: obj.data.materials.append(mat_wide)
    if mat_end.name not in obj.data.materials: obj.data.materials.append(mat_end)
    # Ensure correct indices
    wide_idx = obj.data.materials.find(mat_wide.name)
    end_idx = obj.data.materials.find(mat_end.name)
    
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    for face in bm.faces:
        normal_world = obj.matrix_world.to_3x3() @ face.normal
        dominant_axis = get_face_dominant_axis(normal_world)
        if dominant_axis in end_grain_axes:
            face.material_index = end_idx
        else:
            face.material_index = wide_idx
    bm.to_mesh(obj.data)
    bm.free()
    obj.data.update()

def create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis='Z'):
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    # Link to collection immediately
    collection.objects.link(obj)
    bm = bmesh.new()
    bottom_verts = []
    for v in vertices:
        if extrude_axis == 'Z': vert = bm.verts.new((v[0], v[1], 0))
        elif extrude_axis == 'Y': vert = bm.verts.new((v[0], 0, v[1]))
        elif extrude_axis == 'X': vert = bm.verts.new((0, v[0], v[1]))
        bottom_verts.append(vert)
    bm.verts.ensure_lookup_table()
    if len(bottom_verts) >= 3:
        try: bm.faces.new(bottom_verts)
        except: pass
    if extrude_axis == 'Z': extrude_vec = Vector((0, 0, thickness_m))
    elif extrude_axis == 'Y': extrude_vec = Vector((0, thickness_m, 0))
    elif extrude_axis == 'X': extrude_vec = Vector((thickness_m, 0, 0))
    ret = bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
    verts = [e for e in ret['geom'] if isinstance(e, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=verts, vec=extrude_vec)
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()
    return obj

def create_simple_box(name, width_m, height_m, depth_m, collection):
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    bm = bmesh.new()
    bmesh.ops.create_cube(bm, size=1.0)
    bm.to_mesh(mesh)
    bm.free()
    obj.dimensions = (width_m, depth_m, height_m)
    return obj

def create_cylinder_cutter(name, radius_m, depth_m, collection, segments=32):
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    bm = bmesh.new()
    bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=segments, radius1=radius_m, radius2=radius_m, depth=depth_m)
    bm.to_mesh(mesh)
    bm.free()
    return obj

def apply_boolean_difference(target_obj, cutter_obj, delete_cutter=True):
    success = False
    try:
        bpy.context.view_layer.objects.active = cutter_obj
        cutter_obj.select_set(True)
        bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
        cutter_obj.select_set(False)
        # Check if already has boolean with same name
        if target_obj.modifiers.get("Boolean_Cut"):
            target_obj.modifiers.remove(target_obj.modifiers["Boolean_Cut"])
        bool_mod = target_obj.modifiers.new(name="Boolean_Cut", type='BOOLEAN')
        bool_mod.operation = 'DIFFERENCE'
        bool_mod.object = cutter_obj
        bool_mod.solver = 'EXACT'
        bpy.context.view_layer.objects.active = target_obj
        target_obj.select_set(True)
        bpy.ops.object.modifier_apply(modifier=bool_mod.name)
        target_obj.select_set(False)
        success = True
    except Exception as e:
        print(f"Warning: Boolean failed {e}")
        if "Boolean_Cut" in target_obj.modifiers: target_obj.modifiers.remove(target_obj.modifiers["Boolean_Cut"])
    if delete_cutter:
        try: bpy.data.objects.remove(cutter_obj, do_unlink=True)
        except: pass
    return success

def remove_inner_cap_faces(obj, inner_bound_x, inner_bound_z):
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    faces_to_delete = []
    for face in bm.faces:
        all_inner = True
        for vert in face.verts:
            if abs(vert.co.x) > inner_bound_x + 0.001 or abs(vert.co.z) > inner_bound_z + 0.001:
                all_inner = False
                break
        if all_inner: faces_to_delete.append(face)
    for face in faces_to_delete: bm.faces.remove(face)
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    return len(faces_to_delete)

def remove_hole_cap_faces(obj, hole_positions, y_front, y_back):
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    faces_to_delete = []
    for face in bm.faces:
        centroid = face.calc_center_median()
        y_vals = [v.co.y for v in face.verts]
        if all(abs(y - y_front) < 0.001 for y in y_vals) or all(abs(y - y_back) < 0.001 for y in y_vals):
            for hx, hz in hole_positions:
                dist = ((centroid.x - hx)**2 + (centroid.z - hz)**2)**0.5
                if dist < 0.01:
                    faces_to_delete.append(face)
                    break
    for face in faces_to_delete: bm.faces.remove(face)
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    return len(faces_to_delete)

def create_front_bezel_with_window(name, width_m, height_m, thickness_m, window_w_m, window_h_m, rim_width_m, collection):
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    mesh = obj.data
    bezel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_center_y = (bezel_y_min + bezel_y_max) / 2
    window_w = window_w_m
    window_h = window_h_m
    if window_w > 0 and window_h > 0:
        cutter_mesh = bpy.data.meshes.new(name + "_window_cutter_mesh")
        window_cutter = bpy.data.objects.new(name + "_window_cutter", cutter_mesh)
        collection.objects.link(window_cutter)
        bm = bmesh.new()
        hw = window_w / 2
        hd = thickness_m * 1.5
        hh = window_h / 2
        verts = [bm.verts.new((-hw, -hd, -hh)), bm.verts.new(( hw, -hd, -hh)), bm.verts.new(( hw,  hd, -hh)), bm.verts.new((-hw,  hd, -hh)),
                 bm.verts.new((-hw, -hd,  hh)), bm.verts.new(( hw, -hd,  hh)), bm.verts.new(( hw,  hd,  hh)), bm.verts.new((-hw,  hd,  hh))]
        bm.faces.new([verts[0], verts[1], verts[2], verts[3]])
        bm.faces.new([verts[4], verts[7], verts[6], verts[5]])
        bm.faces.new([verts[0], verts[4], verts[5], verts[1]])
        bm.faces.new([verts[2], verts[6], verts[7], verts[3]])
        bm.faces.new([verts[0], verts[3], verts[7], verts[4]])
        bm.faces.new([verts[1], verts[5], verts[6], verts[2]])
        bm.to_mesh(cutter_mesh)
        bm.free()
        window_cutter.location = (0, bezel_center_y, 0)
        apply_boolean_difference(obj, window_cutter, delete_cutter=True)
        # removed v1.13: remove_inner_cap_faces(obj, window_w/2, window_w/2) 
        # (Boolean difference works correctly, manual removal was deleting walls)
    return obj

def create_back_panel_with_holes(name, width_m, height_m, thickness_m, hole_positions, hole_radius_m, rim_width_m, collection):
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    mesh = obj.data
    panel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_center_y = (panel_y_min + panel_y_max) / 2
    centered_hole_positions = []
    if hole_positions and hole_radius_m > 0:
        for i, (hx, hy) in enumerate(hole_positions):
            hole_cutter = create_cylinder_cutter(f"{name}_hole_{i}", hole_radius_m, thickness_m * 3, collection, segments=16)
            hole_cutter.rotation_euler = (math.pi/2, 0, 0)
            hole_x = hx - width_m/2
            hole_z = hy - height_m/2
            hole_cutter.location = (hole_x, panel_center_y, hole_z)
            centered_hole_positions.append((hole_x, hole_z))
            bpy.context.view_layer.objects.active = hole_cutter
            hole_cutter.select_set(True)
            bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
            hole_cutter.select_set(False)
            apply_boolean_difference(obj, hole_cutter, delete_cutter=True)
        # removed v1.13: remove_hole_cap_faces(...)
    return obj

def create_rail_with_rabbets(name, vertices, thickness_m, collection, fr_w, fr_d, br_w, br_d, length_m, depth_m, extrude_axis='Z'):
    if len(vertices) >= 3: return create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis)
    else: return create_simple_box(name, length_m, thickness_m, depth_m, collection)

def create_french_cleat(name, width_m, height_m, thickness_m, collection, is_wall_part=False):
    # Profile: Rectangle with 45 deg bevel on top/bottom mating edge.
    # Wall Part: Bevel points UP and AWAY from wall? 
    # Standard French Cleat:
    # Wall piece: Screw to wall. Top edge is beveled (low against wall, high away).
    # Box piece: Screw to box. Bottom edge is beveled (low away, high against box).
    # Box piece "hooks" over Wall piece.
    
    # Let's model a simple prism.
    # Profile in X-Y plane (Side View), extruded in X (Width).
    
    # Vertices (Z-Y view):
    # Wall Cleat: 
    # (0,0) -> (Thk, 0) -> (Thk, H-Thk) -> (0, H) -> Close.
    # Wait, Bevel is 45 deg.
    # If Thk is small, bevel is full thickness? Usually.
    
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    
    bm = bmesh.new()
    
    # Profile (looking from Side/Right -> Y-Z plane)
    # Origin at Bottom-Back corner.
    # Wall Cleat (Mounted on Wall): Back is at Y=0 (Wall).
    # Bottom: (0,0). Top Back: (0, H).
    # Top Front: (Thk, H-Thk) [Bevel Tip]
    # Bot Front: (Thk, 0).
    
    # Box Cleat (Mounted on Box): Back is at Y=0 (Box).
    # Top: (0, H) -> (Thk, H).
    # Bot Front: (Thk, Thk). Bot Back: (0, 0).
    # Mates with Wall Cleat.
    
    # NOTE: Our Assembly has explicit positions.
    # Let's make a generic Box: W, H, Thk.
    # Then apply a chamfer or just simple geometry.
    
    # Simple Extrusion along X (Width).
    # Profile in Y-Z.
    
    if is_wall_part:
        # Wall Cleat Profile
        # Back is Z-axis line.
        # Bevel at Top.
        verts = [
            (0, 0), # Bot Back
            (thickness_m, 0), # Bot Front
            (thickness_m, height_m - thickness_m), # Top Front (Bevel Start)
            (0, height_m) # Top Back
        ]
    else:
        # Box Cleat Profile
        # Back is Z-axis line.
        # Bevel at Bottom.
        verts = [
            (0, 0), # Bot Back (Tip)
            (thickness_m, thickness_m), # Bot Front (Bevel End)
            (thickness_m, height_m), # Top Front
            (0, height_m) # Top Back
        ]
        
    # Extrude along X (Width)
    # Center Width?
    # Let's create verts then extrude.
    
    profile_verts = []
    # Shift so Width is Centered on X=0?
    hw = width_m / 2.0
    
    for v_yz in verts:
        # Left Side (X = -hw)
        profile_verts.append(bm.verts.new((-hw, v_yz[0], v_yz[1]))) # Map Y->Y, Z->Z? No, our Profile was Y,Z? 
        # Actually in coords: (X, Y, Z)
        # Profile defined in Y(Depth), Z(Height).
        
    bm.verts.ensure_lookup_table()
    # Make Face
    try: bm.faces.new(profile_verts)
    except: pass
    
    # Extrude to X = +hw
    # Normal extrude vector = (width_m, 0, 0)
    ret = bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
    verts_ext = [e for e in ret['geom'] if isinstance(e, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=verts_ext, vec=(width_m, 0, 0)) # Wait, if we started at -hw, we move full Width.
    
    # Wait, my logic: started at -hw. Moving +width gets to +hw. Correct.
    
    bm.to_mesh(mesh)
    bm.free()
    
    return obj

def create_hatch_lid(name, w, h, thk, flange_w, collection):
    # Complex Lid:
    # Outer Rect (w, h)
    # Boolean cutout (Rabbet) on edges to form step.
    # Simpler: Create Base (Opening size) + Flange (Lid size).
    # Standard Hatch: Lid sits ON TOP of shelf? Or Flush?
    # Usually Flush. So it's Stepped.
    # Top Part: Full W/H, partial thickness.
    # Bot Part: Opening W/H, partial thickness.
    
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    
    bm = bmesh.new()
    
    # Top Plate (Flange)
    # Dimensions: w, h. Thk/2.
    bmesh.ops.create_cube(bm, size=1.0)
    bmesh.ops.scale(bm, vec=(w, thk/2, h), verts=bm.verts) # Y-up thickness?
    # Check orientation. Assembly: Back Panel is in X-Z plane (Vertical). Thickness Y.
    # So Lid Thickness is Y.
    # Top Plate Y center = thk/4.
    bmesh.ops.translate(bm, vec=(0, thk/4, 0), verts=bm.verts)
    
    # Bottom Plate (Insert)
    # Dims: w - 2*flange, h - 2*flange.
    bm2 = bmesh.new()
    bmesh.ops.create_cube(bm2, size=1.0)
    bmesh.ops.scale(bm2, vec=(w - 2*flange_w, thk/2, h - 2*flange_w), verts=bm2.verts)
    bmesh.ops.translate(bm2, vec=(0, -thk/4, 0), verts=bm2.verts)
    
    # Merge
    bm.from_mesh(bm2.to_mesh()) # Simple merge
    bm2.free()
    
    bm.to_mesh(mesh)
    bm.free()
    return obj

def create_shadowbox_assembly():
    print("=" * 60)
    print("Creating McTell Shadowbox in TRIVISION Mode")
    print("Collection: OUTSIDE FRAME")
    print("=" * 60)

    # Create collection "OUTSIDE FRAME" (no scene lighting/unit changes)
    collection_name = "OUTSIDE FRAME"
    collection = bpy.data.collections.get(collection_name)
    if not collection:
        collection = bpy.data.collections.new(collection_name)
        bpy.context.scene.collection.children.link(collection)
    
    # Make it active
    layer_collection = bpy.context.view_layer.layer_collection.children.get(collection_name)
    if layer_collection:
        bpy.context.view_layer.active_layer_collection = layer_collection

    # Create Materials (Reusing if exist)
    mat_wide, mat_end = create_plywood_materials()

    # Create Parts
    stock_thk = CONFIG['STOCK_THICKNESS_M']
    total_w = CONFIG['TOTAL_WIDTH_M']
    total_h = CONFIG['TOTAL_HEIGHT_M']
    box_d = CONFIG['BOX_DEPTH_M']

    parts = {}

    # TOP
    top_verts = parse_svg_path(SVG_PATHS['TOP_RAIL'])
    parts['TOP'] = create_rail_with_rabbets("OUTSIDE_TOP_RAIL", top_verts, stock_thk, collection, 0,0,0,0, total_w, box_d, 'Z')

    # BOTTOM
    bot_verts = parse_svg_path(SVG_PATHS['BOTTOM_RAIL'])
    parts['BOTTOM'] = create_rail_with_rabbets("OUTSIDE_BOTTOM_RAIL", bot_verts, stock_thk, collection, 0,0,0,0, total_w, box_d, 'Z')

    # LEFT
    left_verts = parse_svg_path(SVG_PATHS['LEFT_RAIL'])
    parts['LEFT'] = create_rail_with_rabbets("OUTSIDE_LEFT_RAIL", left_verts, stock_thk, collection, 0,0,0,0, total_h, box_d, 'Z')
    parts['LEFT'].rotation_euler = (0, math.radians(90), 0)

    # RIGHT
    right_verts = parse_svg_path(SVG_PATHS['RIGHT_RAIL'])
    parts['RIGHT'] = create_rail_with_rabbets("OUTSIDE_RIGHT_RAIL", right_verts, stock_thk, collection, 0,0,0,0, total_h, box_d, 'Z')
    parts['RIGHT'].rotation_euler = (0, math.radians(-90), 0)

    # FRONT
    parts['FRONT'] = create_front_bezel_with_window("OUTSIDE_FRONT_BEZEL", total_w, total_h, stock_thk, CONFIG['WINDOW_WIDTH_M'], CONFIG['WINDOW_HEIGHT_M'], CONFIG['FRONT_RIM_WIDTH_M'], collection)

    # BACK
    parts['BACK'] = create_back_panel_with_holes("OUTSIDE_BACK_PANEL", total_w, total_h, stock_thk, BACK_PANEL_HOLES, CONFIG['BACK_HOLE_RADIUS_M'], CONFIG['BACK_RIM_WIDTH_M'], collection)

    # --- v1.10 EXTENSIONS (Cleats + Hatch) ---
    
    # Cleats
    cleat_obj_box = None
    if CONFIG.get('CLEATS_ENABLED', True):
        cw = min(total_w * 0.80, 48.0 * 0.0254) # Match generator logic (inches converted to m already? No generator does it in in)
        # Recalc precisely:
        cw = min(CONFIG['TOTAL_WIDTH_IN'] * 0.80, 48.0) * 0.0254
        ch = 4.0 * 0.0254
        
        # 1. Box Cleat
        cleat_obj_box = create_french_cleat("OUTSIDE_CLEAT_BOX", cw, ch, stock_thk, collection, is_wall_part=False)
        
        # Position:
        # Attached to BACK of Back Panel? Or embedded?
        # Usually screwed to the Back Face of Back Panel.
        # Back Panel Center: (0, box_d/2 + stock/2, 0).
        # Back Face of Back Panel is at Y = box_d/2 + stock.
        # So Cleat Back is at Y = box_d/2 + stock.
        # Height: 1/3 from Top.
        # Top of Frame = +total_h/2.
        # Cleat Center Y (Vertical Z) = (total_h/2) - (total_h/3). = total_h/6.
        # Wait, user said "centered at 1/3... from top".
        # So Z = (TotalH/2) - (TotalH/3).
        
        cleat_z = (total_h / 2.0) - (total_h / 3.0)
        cleat_y = (box_d / 2.0) + stock_thk
        
        # Create Cleat Object
        cleat_obj_box.location = (0, cleat_y, cleat_z)
        
        # Mounting Holes (Boolean)
        # "5%, 33%, 66%, 95%"
        # Create Cylinder Cutters.
        hole_pcts = [0.05, 0.33, 0.66, 0.95]
        # X starts at -cw/2.
        
        for i, pct in enumerate(hole_pcts):
            h_x_local = (-cw/2.0) + (pct * cw)
            # Create Cutter (local to cleat?)
            # Or use global cutter on both Cleat and Back Panel?
            
            # Cutter for Cleat (Countersunk)
            # Simple hole for viz
            cutter = create_cylinder_cutter(f"Cleat_Hole_{i}", 0.005, stock_thk*4, collection) # 5mm radius?
            cutter.rotation_euler = (math.pi/2, 0, 0)
            cutter.location = (h_x_local, 0, 0) # Local to Cleat?
            # Parenting/Transform issue if we use boolean.
            # Easiest: Position cutter globally match cleat.
            cutter.location = (h_x_local, cleat_y, cleat_z)
            
            # Apply to Cleat
            apply_boolean_difference(cleat_obj_box, cutter, delete_cutter=False)
            
            # Apply to Back Panel (Through Hole)
            # Back Panel Object: parts['BACK']
            # Reuse cutter? Yes.
            apply_boolean_difference(parts['BACK'], cutter, delete_cutter=True)

        parts['CLEAT_BOX'] = cleat_obj_box
        
        # 2. Wall Cleat (Mating)
        cleat_obj_wall = create_french_cleat("OUTSIDE_CLEAT_WALL", cw, ch, stock_thk, collection, is_wall_part=True)
        # Mated Position:
        # Wall Cleat slides UNDER/BEHIND Box Cleat.
        # It engages.
        # Geometry: Box Cleat bevel faces IN/Down. Wall Cleat bevel faces OUT/Up.
        # They overlap in Thickness? No, they stack.
        # Wall Cleat is closer to Wall (further +Y).
        # Box Cleat Y = cleat_y.
        # Wall Cleat Y = cleat_y + stock_thk? No, that would be floating.
        # They interlock. 
        # For simple visual: Stack them?
        # Let's put Wall Cleat at Y = cleat_y + stock_thk (simulating wall surface).
        # Z should match (engaged).
        cleat_obj_wall.location = (0, cleat_y + stock_thk, cleat_z)
        parts['CLEAT_WALL'] = cleat_obj_wall
        
    # 5c. CREATE BOTTOM ACCESS HATCH (v1.25)
    if CONFIG.get('BOTTOM_HATCH_ENABLED', False):
        print("[5c/8] Creating Bottom Access Hatch...")
        # Dims from Config (mm -> in -> m)
        bh_w_m = float(CONFIG.get('BOTTOM_HATCH_WIDTH', 0)) * 0.001 
        bh_h_m = float(CONFIG.get('BOTTOM_HATCH_HEIGHT', 0)) * 0.001
        bh_x_pct = float(CONFIG.get('BOTTOM_HATCH_X_PCT', 50.0))
        
        # Flange logic
        glue_gap = 0.0005 
        flange_w = (stock_thk / 2.0) - glue_gap
        if flange_w < 0.001: flange_w = 0.001

        # Create Hatch Lid Object
        bh_obj = create_hatch_lid("OUTSIDE_BOTTOM_HATCH_LID", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        inner_w = total_w - (2 * stock_thk)
        bx = (-(total_w/2) + stock_thk) + (bh_x_pct / 100.0 * inner_w)
        
        # Rotation (Flat on Bottom)
        bh_obj.rotation_euler = (math.radians(90), 0, 0)
        
        # Location (Centered in Depth Y=0, Bottom of Box Z)
        # Bottom Rail Z = -half_h + stock_thk/2.
        bh_obj.location = (bx, 0, -half_h + stock_thk/2)
        
        parts['BOTTOM_HATCH'] = bh_obj
        
        # Cutout in Bottom Rail
        # 1. Through Cut
        c1 = create_simple_box("Bottom_Hatch_Cut_Thru", bh_w_m, bh_h_m, stock_thk*4, collection)
        c1.location = (bx, 0, -half_h + stock_thk/2)
        apply_boolean_difference(parts['BOTTOM'], c1, delete_cutter=True)
        
        # 2. Pocket Cut (Shelf)
        # From Outside (Bottom) Face Inwards.
        # Bottom Face Z = -half_h.
        # Pocket Depth = stock/2.
        # Cutter Z = -half_h + stock/4.
        c2 = create_simple_box("Bottom_Hatch_Cut_Pocket", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk/2, collection)
        c2.location = (bx, 0, -half_h + (stock_thk * 0.25))
        apply_boolean_difference(parts['BOTTOM'], c2, delete_cutter=True)

    # Hatch Lid (Rear)
    if CONFIG.get('HATCH_ENABLED', False):
        # Create Hatch Lid
        # Dims
        h_w_pct = CONFIG.get('HATCH_WIDTH_PCT', 50.0) / 100.0
        h_h_pct = CONFIG.get('HATCH_HEIGHT_PCT', 33.0) / 100.0
        h_open_w = total_w * h_w_pct
        h_open_h = total_h * h_h_pct
        
        glue_gap = 0.0005 # approx
        flange_w = (stock_thk / 2.0) - glue_gap
        
        hatch_obj = create_hatch_lid("OUTSIDE_HATCH_LID", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        # Position: Center X, Back Face Y, Z determined by Raise
        # Base Z = Bottom of Box (-H/2) + Stock + Raise
        base_z = (-total_h / 2.0) + stock_thk + raise_m
        
        # Hatch Center Z = Base Z + (Hatch Open H / 2) + Flange?
        # Hatch Object Origin is Center.
        # Ideally match the cutout.
        # The Cutout Center Z = Base Z + (h_open_h / 2).
        hatch_z = base_z + (h_open_h / 2.0)
        
        hatch_y = (box_d / 2.0) # Flush with Inside Face?
        # Back Panel: Thick Z (Y in global). Center Y = box_d/2 + stock/2.
        # Inside Face = box_d/2.
        # Hatch usually flush with inside?
        # Yes.
        
        hatch_obj.location = (0, hatch_y, hatch_z)
        # Check orientation: create_hatch_lid made it flat (X-Z)? scaled Y=Thk.
        # Yes. 
        
        parts['HATCH'] = hatch_obj
        
        # Cutout in Back Panel
        # We need to cut the Back Panel to accept the Hatch.
        # Opening (Through) + Shelf (Pocket).
        # Let's just cut the Opening for visual simplicity?
        # Or proper stepped boolean?
        # Create Stepped Cutter.
        # Cutter 1: Through (Inner Size).
        c1 = create_simple_box("Hatch_Cut_Thru", h_open_w, h_open_h, stock_thk*4, collection)
        c1.location = (0, hatch_y, hatch_z)
        apply_boolean_difference(parts['BACK'], c1, delete_cutter=True)
        
        # Cutter 2: Flange (Pocket from Outside Face).
        # Outside Face Y = box_d/2 + stock.
        # Pocket depth = stock/2.
        # Cutter size: Full Lid Size.
        # Cutter Y pos: Outside Face.
        # We want to remove material from Outside Face inwards.
        c2 = create_simple_box("Hatch_Cut_Pocket", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, collection)
        # Position: Center matches. Y needs to overlap outward half.
        # Back Panel Y range: [box_d/2, box_d/2 + stock].
        # We want to cut [box_d/2 + stock/2, box_d/2 + stock].
        # Center of cut region: box_d/2 + 0.75*stock.
        c2.location = (0, (box_d/2.0) + (stock_thk * 0.75), hatch_z)
        apply_boolean_difference(parts['BACK'], c2, delete_cutter=True)
        
    # Position Parts

    half_w = total_w / 2
    half_h = total_h / 2
    half_d = box_d / 2

    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
        obj.select_set(False)

    top_rail_width = parts['TOP'].dimensions.x
    finger_tip_x = top_rail_width / 2

    parts['TOP'].location = (0, 0, half_h - stock_thk/2)
    parts['BOTTOM'].location = (0, 0, -half_h + stock_thk/2)
    parts['LEFT'].location = (-finger_tip_x + stock_thk/2, 0, 0)
    parts['RIGHT'].location = (finger_tip_x - stock_thk/2, 0, 0)
    parts['FRONT'].location = (0, -half_d - stock_thk/2, 0)
    parts['BACK'].location = (0, half_d + stock_thk/2, 0)

    # Transforms & Materials
    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
        obj.select_set(False)

    end_grain_config = {
        'TOP': ['X'], 'BOTTOM': ['X'],
        'LEFT': ['Z'], 'RIGHT': ['Z'],
        'FRONT': ['X', 'Z'], 'BACK': ['X', 'Z'],
    }

    for key, obj in parts.items():
        apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_config.get(key, []))

    # Parent all parts to a main Empty for unified movement
    root_empty = bpy.data.objects.new("OUTSIDE FRAME", None)
    collection.objects.link(root_empty)
    
    # Hardcoded Transform: REMOVED per User Request (Center at 0,0,0)
    root_empty.location = (0, 0, 0)
    # Rotation: Keep 180 flip if it orients 'Front' correctly to camera default
    root_empty.rotation_euler = (0, 0, 3.141593)
    
    root_empty.empty_display_type = 'CUBE'
    root_empty.empty_display_size = 0.5
    
    # ADD LIGHTING ("OUTSIDE LIGHT")
    # Area light positioned to illuminate the front/top of the box
    light_data = bpy.data.lights.new(name="OUTSIDE LIGHT", type='AREA')
    light_data.color = (1.0, 1.0, 1.0)
    light_data.energy = 50.0  # Adjust as needed
    light_data.shape = 'SQUARE'
    light_data.size = 1.0     # 1 meter size
    
    light_obj = bpy.data.objects.new("OUTSIDE LIGHT", light_data)
    collection.objects.link(light_obj)
    
    # Initial Position (Relative to Box "Front" at -Y)
    # Place it in front (-Y) and above (+Z)
    light_obj.location = (0, -1.0, 1.0) 
    # Point it at the box (Rotate X positive to point "back" along +Y and down -Z?)
    # Default Area light points -Z.
    # Rot X +45deg -> Points -Z and +Y (Towards back)
    light_obj.rotation_euler = (math.radians(45), 0, 0)
    
    parts['LIGHT'] = light_obj  # Add to parts dict to participate in flip/parent loop
    
    # FLIP GEOMETRY 180 degrees internally
    for key, obj in parts.items():
        # Rotate location 180 deg around Z (which flips X and Y)
        # x' = x*cos(180) - y*sin(180) = -x
        # y' = x*sin(180) + y*cos(180) = -y
        obj.location.x = -obj.location.x
        obj.location.y = -obj.location.y
        # Add 180 deg to rotation
        obj.rotation_euler.z += math.pi

    for key, obj in parts.items():
        obj.parent = root_empty
        obj.matrix_parent_inverse = root_empty.matrix_world.inverted()

    print("Generation complete in collection 'OUTSIDE FRAME'")
    
    # 8. CONFIGURE VIEWPORT (Fix for Zoom Clipping)
    print("[8/8] Configuring Viewport settings...")
    for scr in bpy.data.screens:
        for area in scr.areas:
            if area.type == 'VIEW_3D':
                for space in area.spaces:
                    if space.type == 'VIEW_3D':
                        # Set Clip Start to 1mm to allow close zoom
                        space.clip_start = 0.001
                        # Ensure shading is nice
                        space.shading.type = 'MATERIAL'
                        space.shading.use_scene_lights = True
                        space.shading.use_scene_world = True

if __name__ == "__main__":
    create_shadowbox_assembly()
